// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SOFTWARE1_PROYECTO.Data;

namespace SOFTWARE1_PROYECTO.Data.Migrations
{
    [DbContext(typeof(InventarioContext))]
    [Migration("20201203223000_CreateIdentitySchema")]
    partial class CreateIdentitySchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SOFTWARE1_PROYECTO.Models.Producto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("cantidad")
                        .HasColumnName("cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("color")
                        .HasColumnName("color")
                        .HasColumnType("text");

                    b.Property<string>("modelo")
                        .HasColumnName("modelo")
                        .HasColumnType("text");

                    b.Property<string>("product")
                        .HasColumnName("product")
                        .HasColumnType("text");

                    b.Property<string>("sexo")
                        .HasColumnName("sexo")
                        .HasColumnType("text");

                    b.Property<string>("tallas")
                        .HasColumnName("tallas")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("t_producto");
                });

            modelBuilder.Entity("SOFTWARE1_PROYECTO.Models.Registrar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Apellido")
                        .HasColumnName("apellido")
                        .HasColumnType("text");

                    b.Property<string>("Cargo")
                        .HasColumnName("cargo")
                        .HasColumnType("text");

                    b.Property<string>("Contraseña")
                        .HasColumnName("contraseña")
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .HasColumnName("correo")
                        .HasColumnType("text");

                    b.Property<string>("DNI")
                        .HasColumnName("dni")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasColumnName("nombre")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("t_usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
