// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SOFTWARE1_PROYECTO.Data;

namespace SOFTWARE1_PROYECTO.Migrations
{
    [DbContext(typeof(InventarioContext))]
    partial class InventarioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SOFTWARE1_PROYECTO.Models.Cliente", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnName("apellido")
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasColumnType("text");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnName("dni")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.Property<string>("celular")
                        .IsRequired()
                        .HasColumnName("celular")
                        .HasColumnType("text");

                    b.Property<int>("compras")
                        .HasColumnName("compras")
                        .HasColumnType("integer");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnName("direccion")
                        .HasColumnType("text");

                    b.Property<string>("distrito")
                        .IsRequired()
                        .HasColumnName("distrito")
                        .HasColumnType("text");

                    b.Property<string>("sexo")
                        .IsRequired()
                        .HasColumnName("sexo")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("t_cliente");
                });

            modelBuilder.Entity("SOFTWARE1_PROYECTO.Models.EntradaProducto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<int>("cantidadEntrada")
                        .HasColumnName("cantidadEntrada")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("ProductoId");

                    b.ToTable("t_EntradaProducto");
                });

            modelBuilder.Entity("SOFTWARE1_PROYECTO.Models.Producto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("cantidad")
                        .HasColumnName("cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("color")
                        .IsRequired()
                        .HasColumnName("color")
                        .HasColumnType("text");

                    b.Property<string>("modelo")
                        .IsRequired()
                        .HasColumnName("modelo")
                        .HasColumnType("text");

                    b.Property<string>("product")
                        .IsRequired()
                        .HasColumnName("product")
                        .HasColumnType("text");

                    b.Property<string>("sexo")
                        .IsRequired()
                        .HasColumnName("sexo")
                        .HasColumnType("text");

                    b.Property<string>("tallas")
                        .IsRequired()
                        .HasColumnName("tallas")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("t_producto");
                });

            modelBuilder.Entity("SOFTWARE1_PROYECTO.Models.Registrar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Apellido")
                        .HasColumnName("apellido")
                        .HasColumnType("text");

                    b.Property<string>("Cargo")
                        .HasColumnName("cargo")
                        .HasColumnType("text");

                    b.Property<string>("Contraseña")
                        .HasColumnName("contraseña")
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .HasColumnName("correo")
                        .HasColumnType("text");

                    b.Property<string>("DNI")
                        .HasColumnName("dni")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasColumnName("nombre")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("t_usuario");
                });

            modelBuilder.Entity("SOFTWARE1_PROYECTO.Models.EntradaProducto", b =>
                {
                    b.HasOne("SOFTWARE1_PROYECTO.Models.Producto", "producto")
                        .WithMany("EntradaProductos")
                        .HasForeignKey("ProductoId");
                });
#pragma warning restore 612, 618
        }
    }
}
